### ISSUE TITLE
Single camera works, multiple cameras show me an error

### ISSUE THREAD

**Issue by selmaohneh** [dermotduffy/advanced-camera-card#636] opened 2022-06-07 15:04 UTC
I am trying to integrate a second camera. But I can't get the config to work ...

* Using each camera standalone using the `camera_entity` syntax works like a charm.
* As soon as I try to add multiple cameras using the `cameras:` syntax, I get an error that the camera_entity and/or the camera_name needs to be specified - which I thought I did.

What am I doing wrong?

```
type: custom:frigate-card
cameras:
  - camera_entity: camera.backyard
  - camera_entity: camera.frontyard
view:
  default: snapshots
menu:
  buttons:
    frigate: false
```

**Comment by dermotduffy** [comment] 2022-06-07 15:25
Can you paste in the text of the config (not screenshot) for the multiple cameras, and a screenshot of the error you receive. The second syntax in your screenshot looks right, as long as you're using at least v3 of the card.

**Comment by selmaohneh** [comment] 2022-06-07 15:43
* Edited the issue to now contain the text.
* Just did the update to v3. Restarted the server.
* Same issue.

Here is the screenshot:
 
![image](https://user-images.githubusercontent.com/29881939/172423534-ef42f06c-964a-49b6-a5cd-ce7fb7336376.png)

**Comment by dermotduffy** [comment] 2022-06-07 18:14
Are you using a recent Frigate integration version? Latest is 2.3. Are they definitely Frigate camera entities (i.e. when you navigate to the Frigate integration in settings, do those entities show up?). The camera name auto detection only works for native Frigate cameras.

**Comment by dermotduffy** [comment] 2022-06-07 18:15
If you just installed card v3, also make sure to flush your cache. (e.g. try it in an incognito window and see if you get the same result)

**Comment by selmaohneh** [comment] 2022-06-08 04:42
* I am using Frigate v2.3.
* The entities are definitely Frigate camera entities, just checked.
* Flushing the cache was a good point. Did that and tried the incognito mode. Result: The error is gone.
* But: Only the snapshots of the first camera get shown. So my config still seems to be wrong, i.e. the second camera gets ignored.
* Further ideas? Thanks already!

**Comment by dermotduffy** [comment] 2022-06-08 04:45
Can you change to the second camera via the camera selector button? What happens if you change to the second camera, and then click the snapshots or clips button?

**Comment by selmaohneh** [comment] 2022-06-08 06:31
I enabled the frigate button and swapped the order of both cameras in the config:

```
type: custom:frigate-card
cameras:
  - camera_entity: camera.frontyard
  - camera_entity: camera.backyard
view:
  default: snapshots
menu:
  buttons:
    frigate: true
```

Now only the snapshots of the frontyard camera get shown. So in conclusion only the snapshots of the camera mentioned first in the config get shown.

I am able to swap between the cameras via the Frigate / Select camera button though. I can view the snapshots of both cameras seperatley that way - but still not merged. :-/

**Comment by dermotduffy** [comment] 2022-06-08 06:36
Hmm, so you can see the media after you select the camera in the camera select menu, but you're not seeing them merged? That is working as intended then. You should be able to see the clips/snapshots of whatever camera you have selected in the camera select menu. There is no merging.

In the v4 code, which is close to release, there's a concept of a dependent camera, and media of dependent cameras are merged together. Maybe this is what you were expecting to happen?

(I also may be misunderstanding, a short video clip of what you are seeing would be welcome if I'm still not getting it)

**Comment by selmaohneh** [comment] 2022-06-08 11:13
Yeah - updating the card solved the error. The remaining problem was my idea of the concept:

I thought I setup two cameras and when opening the card I see the snapshots of both cameras in the same view merged, i.e. no need to switch between cameras inside the view.

But if that is currently not a feature, consider this issue closed and I'll wait for v4 :-)

**Comment by dermotduffy** [comment] 2022-06-08 13:53
> I thought I setup two cameras and when opening the card I see the snapshots of both cameras in the same view merged, i.e. no need to switch between cameras inside the view.

Yeah, it's more about allowing you to choose which camera you are viewing streams/clips from, than attempting a merged view. I haven't had someone ask for this before.

How many cameras are you planning to merge? With the new dependent cameras feature this will be possible, but it would be pretty annoying if you had 10 cameras (as for each one, you'd need to specify the other 9 are dependents). This feature is more imagined so a camera showing the birdseye view can fetch events from all cameras that contribute to that birdseye view. That's a bit different from "all clips/snapshots should be merged from all cameras at all time".

**Comment by selmaohneh** [comment] 2022-06-08 15:58
I will have 3 cameras maximum [tm].

I just have a camera icon on my dashboard. 

As soon as one of my cameras sees a person around the house the icon turns red and I know I should take a look at the snapshots.

The icon opens a popup with your wonderful frigate card. That's when I expected to see all snapsshots from all cameras at once. 

That's my use case.

![Screenshot_20220608_175316.jpg](https://user-images.githubusercontent.com/29881939/172663155-a88be2b2-e5fe-4922-8b24-1f0e0a7b7234.jpg)

Feel free to close. Thanks for all the help!

**Closed as completed** 2022-06-10 16:27 UTC
Labels: question

**Comment by selmaohneh** [comment] 2022-07-06 16:06
Looks promising! Is there some kind of roadmap or something similar? Otherwise I would have to annoy you every few days by asking when the new version will be released? :-D

**Comment by dermotduffy** [comment] 2022-07-07 00:33
Hi @selmaohneh , there's already a v4 pre-release: https://github.com/dermotduffy/frigate-hass-card/releases/tag/v4.0.0-rc.2 .

[See this description of how to use a pre-release](https://github.com/blakeblackshear/frigate/discussions/1590#discussioncomment-3071389) if you're not familiar.

Good luck / Enjoy!
